export const SIMULATION_TOPIC_TO_EVALUATION_MODULE: Record<string, string> = {
  acute_abdominal_pain: 'cpx-01-acute_abdominal_pain',
  dyspepsia_chronic_abdominal_pain: 'cpx-02-dyspepsia_chronic_abdominal_pain',
  hematemesis: 'cpx-03-hematemesis',
  hematochezia: 'cpx-04-hematochezia',
  vomiting: 'cpx-05-vomiting',
  constipation: 'cpx-06-bowel_habit_change',
  diarrhea: 'cpx-06-bowel_habit_change',
  jaundice: 'cpx-07-jaundice',
  chest_pain: 'cpx-08-chest_pain',
  syncope: 'cpx-09-syncope',
  palpitation: 'cpx-10-palpitation',
  hypertension: 'cpx-11-hypertension',
  dyslipidemia: 'cpx-12-dyslipidemia',
  cough: 'cpx-13-cough',
  rhinorrhea_nasal_congestion: 'cpx-14-rhinorrhea_nasal_congestion',
  hemoptysis: 'cpx-15-hemoptysis',
  dyspnea: 'cpx-16-dyspnea',
  polyuria: 'cpx-17-urine_volume_change',
  oliguria: 'cpx-17-urine_volume_change',
  red_urine: 'cpx-18-red_urine',
  voiding_dysfunction: 'cpx-19-voiding_dysfunction',
  urinary_incontinence: 'cpx-19-voiding_dysfunction',
  fever: 'cpx-20-fever',
  easy_bruising: 'cpx-21-easy_bruising',
  fatigue: 'cpx-22-fatigue',
  weight_loss: 'cpx-23-weight_loss',
  weight_gain_obesity: 'cpx-24-weight_gain_obesity',
  joint_pain_swelling: 'cpx-25-joint_pain_swelling',
  neck_pain: 'cpx-26-neck_low_back_pain',
  low_back_pain: 'cpx-26-neck_low_back_pain',
  skin_rash: 'cpx-27-skin_rash',
  mood_change: 'cpx-28-mood_change',
  anxiety: 'cpx-29-anxiety',
  sleep_disturbance: 'cpx-30-sleep_disorder',
  memory_decline: 'cpx-31-memory_decline',
  dizziness: 'cpx-32-dizziness',
  headache: 'cpx-33-headache',
  seizure: 'cpx-34-seizure',
  motor_sensory_deficit: 'cpx-35-motor_sensory_abnormality',
  altered_consciousness: 'cpx-36-altered_mental_status',
  tremor_movement_disorder: 'cpx-37-tremor_movement_disorder',
  breast_pain_lump: 'cpx-38-breast_pain_lump',
  vaginal_discharge: 'cpx-39-vaginal_discharge_bleeding',
  vaginal_bleeding: 'cpx-39-vaginal_discharge_bleeding',
  menstrual_abnormality: 'cpx-40-menstrual_abnormality_dysmenorrhea',
  dysmenorrhea: 'cpx-40-menstrual_abnormality_dysmenorrhea',
  prenatal_care: 'cpx-41-prenatal_care',
  growth_development_delay: 'cpx-42-growth_developmental_delay',
  vaccination: 'cpx-43-vaccination',
  alcohol_counseling: 'cpx-44-alcohol_smoking_counseling',
  smoking_cessation_counseling: 'cpx-44-alcohol_smoking_counseling',
  substance_misuse: 'cpx-45-substance_misuse',
  breaking_bad_news: 'cpx-46-breaking_bad_news',
  domestic_violence: 'cpx-47-domestic_sexual_violence',
  sexual_violence: 'cpx-47-domestic_sexual_violence',
  suicide_risk: 'cpx-48-suicide_risk',
};

export function evaluationModuleForSimulationTopic(
  topicId: string | null | undefined,
): string | null {
  if (!topicId) return null;
  return SIMULATION_TOPIC_TO_EVALUATION_MODULE[topicId] ?? null;
}
